/***********************************************************************
* Copyright by Michael Loesler, https://software.applied-geodesy.org   *
*                                                                      *
* This program is free software; you can redistribute it and/or modify *
* it under the terms of the GNU General Public License as published by *
* the Free Software Foundation; either version 3 of the License, or    *
* at your option any later version.                                    *
*                                                                      *
* This program is distributed in the hope that it will be useful,      *
* but WITHOUT ANY WARRANTY; without even the implied warranty of       *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        *
* GNU General Public License for more details.                         *
*                                                                      *
* You should have received a copy of the GNU General Public License    *
* along with this program; if not, see <http://www.gnu.org/licenses/>  *
* or write to the                                                      *
* Free Software Foundation, Inc.,                                      *
* 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.            *
*                                                                      *
***********************************************************************/

package org.applied_geodesy.instrument.totalstaion.leica.es;

public enum GRC {
	GRC_OK (0, "Function successfully completed."),
	GRC_UNDEFINED (1, "Unknown error, result unspecified."),
	GRC_IVPARAM (2, "Invalid parameter detected. Result unspecified."),
	GRC_IVRESULT (3, "Invalid result."),
	GRC_FATAL (4, "Fatal error."),
	GRC_NOT_IMPL (5, "Not implemented yet."),
	GRC_TIME_OUT (6, "Function execution timed out. Result unspecified."),
	GRC_SET_INCOMPL (7, "Parameter setup for subsystem is incomplete."),
	GRC_ABORT (8, "Function execution has been aborted."),
	GRC_NOMEMORY (9, "Fatal error - not enough memory."),
	GRC_NOTINIT (10, "Fatal error - subsystem not initialized."),
	GRC_SHUT_DOWN (12, "Subsystem is down."),
	GRC_SYSBUSY (13, "System busy/already in use of another process. Cannot execute function."),
	GRC_HWFAILURE (14, "Fatal error - hardware failure."),
	GRC_ABORT_APPL (15, "Execution of application has been aborted (SHIFT-ESC)."),
	GRC_LOW_POWER (16, "Operation aborted - insufficient power supply level."),
	GRC_IVVERSION (17, "Invalid version of file, ..."),
	GRC_BATT_EMPTY (18, "Battery empty"),
	GRC_NO_EVENT (20, "no event pending."),
	GRC_OUT_OF_TEMP (21, "out of temperature range"),
	GRC_INSTRUMENT_TILT (22, "instrument tilting out of range"),
	GRC_COM_SETTING (23, "communication error"),
	GRC_NO_ACTION (24, "GRC_TYPE Input 'do no action'"),
	GRC_SLEEP_MODE (25, "Instr. run into the sleep mode"),
	GRC_NOTOK (26, "Function not successfully completed."),
	GRC_NA (27, "Not available"),
	GRC_OVERFLOW (28, "Overflow error"),
	GRC_STOPPED (29, "System or subsystem has been stopped"),
	GRC_ANG_ERROR (257, "Angles and Inclinations not valid"),
	GRC_ANG_INCL_ERROR (258, "inclinations not valid"),
	GRC_ANG_BAD_ACC (259, "value accuracies not reached"),
	GRC_ANG_BAD_ANGLE_ACC (260, "angle-accuracies not reached"),
	GRC_ANG_BAD_INCLIN_ACC (261, "inclination accuracies not reached"),
	GRC_ANG_WRITE_PROTECTED (266, "no write access allowed"),
	GRC_ANG_OUT_OF_RANGE (267, "value out of range"),
	GRC_ANG_IR_OCCURED (268, "function aborted due to interrupt"),
	GRC_ANG_HZ_MOVED (269, "hz moved during incline measurement"),
	GRC_ANG_OS_ERROR (270, "troubles with operation system"),
	GRC_ANG_DATA_ERROR (271, "overflow at parameter values"),
	GRC_ANG_PEAK_CNT_UFL (272, "too less peaks"),
	GRC_ANG_TIME_OUT (273, "reading timeout"),
	GRC_ANG_TOO_MANY_EXPOS (274, "too many exposures wanted"),
	GRC_ANG_PIX_CTRL_ERR (275, "picture height out of range"),
	GRC_ANG_MAX_POS_SKIP (276, "positive exposure dynamic overflow"),
	GRC_ANG_MAX_NEG_SKIP (277, "negative exposure dynamic overflow"),
	GRC_ANG_EXP_LIMIT (278, "exposure time overflow"),
	GRC_ANG_UNDER_EXPOSURE (279, "picture underexposured"),
	GRC_ANG_OVER_EXPOSURE (280, "picture overexposured"),
	GRC_ANG_TMANY_PEAKS (300, "too many peaks detected"),
	GRC_ANG_TLESS_PEAKS (301, "too less peaks detected"),
	GRC_ANG_PEAK_TOO_SLIM (302, "peak too slim"),
	GRC_ANG_PEAK_TOO_WIDE (303, "peak to wide"),
	GRC_ANG_BAD_PEAKDIFF (304, "bad peak difference"),
	GRC_ANG_UNDER_EXP_PICT (305, "too less peak amplitude"),
	GRC_ANG_PEAKS_INHOMOGEN (306, "inhomogeneous peak amplitudes"),
	GRC_ANG_NO_DECOD_POSS (307, "no peak decoding possible"),
	GRC_ANG_UNSTABLE_DECOD (308, "peak decoding not stable"),
	GRC_ANG_TLESS_FPEAKS (309, "too less valid finepeaks"),
	GRC_ANG_INCL_OLD_PLANE (316, "inclination plane out of time range"),
	GRC_ANG_INCL_NO_PLANE (317, "inclination no plane available"),
	GRC_ANG_FAST_ANG_ERR (326, "errors in 5kHz and or 2.5kHz angle"),
	GRC_ANG_FAST_ANG_ERR_5 (327, "errors in 5kHz angle"),
	GRC_ANG_FAST_ANG_ERR_25 (328, "errors in 2.5kHz angle"),
	GRC_ANG_TRANS_ERR (329, "LVDS transfer error detected"),
	GRC_ANG_TRANS_ERR_5 (330, "LVDS transfer error detected in 5kHz mode"),
	GRC_ANG_TRANS_ERR_25 (331, "LVDS transfer error detected in 2.5kHz mode"),
	GRC_ATA_NOT_READY (512, "ATR-System is not ready."),
	GRC_ATA_NO_RESULT (513, "Result isn't available yet."),
	GRC_ATA_SEVERAL_TARGETS (514, "Several Targets detected."),
	GRC_ATA_BIG_SPOT (515, "Spot is too big for analyse."),
	GRC_ATA_BACKGROUND (516, "Background is too bright."),
	GRC_ATA_NO_TARGETS (517, "No targets detected."),
	GRC_ATA_NOT_ACCURAT (518, "Accuracy worse than asked for."),
	GRC_ATA_SPOT_ON_EDGE (519, "Spot is on the edge of the sensing area."),
	GRC_ATA_BLOOMING (522, "Blooming or spot on edge detected."),
	GRC_ATA_NOT_BUSY (523, "ATR isn't in a continuous mode."),
	GRC_ATA_STRANGE_LIGHT (524, "Not the spot of the own target illuminator."),
	GRC_ATA_V24_FAIL (525, "Communication error to sensor (ATR)."),
	GRC_ATA_DECODE_ERROR (526, "Received Arguments cannot be decoded"),
	GRC_ATA_HZ_FAIL (527, "No Spot detected in Hz-direction."),
	GRC_ATA_V_FAIL (528, "No Spot detected in V-direction."),
	GRC_ATA_HZ_STRANGE_L (529, "Strange light in Hz-direction."),
	GRC_ATA_V_STRANGE_L (530, "Strange light in V-direction."),
	GRC_ATA_SLDR_TRANSFER_PENDING (531, "On multiple ATA_SLDR_OpenTransfer."),
	GRC_ATA_SLDR_TRANSFER_ILLEGAL (532, "No ATA_SLDR_OpenTransfer happened."),
	GRC_ATA_SLDR_DATA_ERROR (533, "Unexpected data format received."),
	GRC_ATA_SLDR_CHK_SUM_ERROR (534, "Checksum error in transmitted data."),
	GRC_ATA_SLDR_ADDRESS_ERROR (535, "Address out of valid range."),
	GRC_ATA_SLDR_INV_LOADFILE (536, "Firmware file has invalid format."),
	GRC_ATA_SLDR_UNSUPPORTED (537, "Current (loaded) firmware doesn't support upload."),
	GRC_ATA_PS_NOT_READY (538, "PS-System is not ready."),
	GRC_ATA_ATR_SYSTEM_ERR (539, "ATR system error"),
	GRC_EDM_SYSTEM_ERR (769, "Fatal EDM sensor error. See for the exact reason the original EDM sensor error number. In the most cases a service problem."),
	GRC_EDM_INVALID_COMMAND (770, "Invalid command or unknown command, see command syntax."),
	GRC_EDM_BOOM_ERR (771, "Boomerang error."),
	GRC_EDM_SIGN_LOW_ERR (772, "Received signal to low, prism to far away, or natural barrier, bad environment, etc."),
	GRC_EDM_DIL_ERR (773, "obsolete"),
	GRC_EDM_SIGN_HIGH_ERR (774, "Received signal to strong, prism to near, stranger light effect."),
	GRC_EDM_TIMEOUT (775, "Timeout, measuring time exceeded (signal too weak, beam interrupted,..)"),
	GRC_EDM_FLUKT_ERR (776, "to much turbulences or distractions"),
	GRC_EDM_FMOT_ERR (777, "filter motor defective"),
	GRC_EDM_DEV_NOT_INSTALLED (778, "Device like EGL, DL is not installed."),
	GRC_EDM_NOT_FOUND (779, "Search result invalid. For the exact explanation, see in the description of the called function."),
	GRC_EDM_ERROR_RECEIVED (780, "Communication ok, but an error reported from the EDM sensor."),
	GRC_EDM_MISSING_SRVPWD (781, "No service password is set."),
	GRC_EDM_INVALID_ANSWER (782, "Communication ok, but an unexpected answer received."),
	GRC_EDM_SEND_ERR (783, "Data send error, sending buffer is full."),
	GRC_EDM_RECEIVE_ERR (784, "Data receive error, like parity buffer overflow."),
	GRC_EDM_INTERNAL_ERR (785, "Internal EDM subsystem error."),
	GRC_EDM_BUSY (786, "Sensor is working already, abort current measuring first."),
	GRC_EDM_NO_MEASACTIVITY (787, "No measurement activity started."),
	GRC_EDM_CHKSUM_ERR (788, "Calculated checksum, resp. received data wrong (only in binary communication mode possible)."),
	GRC_EDM_INIT_OR_STOP_ERR (789, "During start up or shut down phase an error occured. It is saved in the DEL buffer."),
	GRC_EDM_SRL_NOT_AVAILABLE (790, "Red laser not available on this sensor HW."),
	GRC_EDM_MEAS_ABORTED (791, "Measurement will be aborted (will be used for the laser security)"),
	GRC_EDM_SLDR_TRANSFER_PENDING (798, "Multiple OpenTransfer calls."),
	GRC_EDM_SLDR_TRANSFER_ILLEGAL (799, "No open transfer happened."),
	GRC_EDM_SLDR_DATA_ERROR (800, "Unexpected data format received."),
	GRC_EDM_SLDR_CHK_SUM_ERROR (801, "Checksum error in transmitted data."),
	GRC_EDM_SLDR_ADDR_ERROR (802, "Address out of valid range."),
	GRC_EDM_SLDR_INV_LOADFILE (803, "Firmware file has invalid format."),
	GRC_EDM_SLDR_UNSUPPORTED (804, "Current (loaded) firmware doesn't support upload."),
	GRC_EDM_UNKNOW_ERR (808, "Undocumented error from the EDM sensor, should not occur."),
	GRC_EDM_DISTRANGE_ERR (818, "Out of distance range (dist too small or large)"),
	GRC_EDM_SIGNTONOISE_ERR (819, "Signal to noise ratio too small"),
	GRC_EDM_NOISEHIGH_ERR (820, "Noise to high"),
	GRC_EDM_PWD_NOTSET (821, "Password is not set"),
	GRC_EDM_ACTION_NO_MORE_VALID (822, "Elapsed time between prepare und start fast measurement for ATR to long"),
	GRC_EDM_MULTRG_ERR (823, "Possibly more than one target (also a sensor error)"),
	GRC_EDM_MISSING_EE_CONSTS (824, "eeprom consts are missing"),
	GRC_EDM_NOPRECISE (825, "No precise measurement possible"),
	GRC_EDM_MEAS_DIST_NOT_ALLOWED (826, "Measured distance is to big (not allowed)"),
	GRC_EDM_NOT_EXECUTED (827, "Part or whole measurement was not executed"),
	GRC_EDM_SIG_FORM_ERR (828, "Sinus signal form error"),
	GRC_EDM_DIST_TOO_SHORT (829, "Measured distance too short"),
	GRC_EDM_SYNTH_ERR (830, "PLL-spg out of tolerance"),
	GRC_EDM_AMPL_RELATION_ERR (831, "Amplitude relation fine / rough error"),
	GRC_EDM_DIVISION_BY_ZERO (832, "Division by zero"),
	GRC_TMC_NO_FULL_CORRECTION (1283, "Warning: measurement without full correction"),
	GRC_TMC_ACCURACY_GUARANTEE (1284, "Info: accuracy can not be guarantee"),
	GRC_TMC_ANGLE_OK (1285, "Warning: only angle measurement valid"),
	GRC_TMC_ANGLE_NOT_FULL_CORR (1288, "Warning: only angle measurement valid but without full correction"),
	GRC_TMC_ANGLE_NO_ACC_GUARANTY (1289, "Info: only angle measurement valid but accuracy can not be guarantee"),
	GRC_TMC_ANGLE_ERROR (1290, "Error: no angle measurement"),
	GRC_TMC_DIST_PPM (1291, "Error: wrong setting of PPM or MM on EDM"),
	GRC_TMC_DIST_ERROR (1292, "Error: distance measurement not done (no aim, etc.)"),
	GRC_TMC_BUSY (1293, "Error: system is busy (no measurement done)"),
	GRC_TMC_SIGNAL_ERROR (1294, "Error: no signal on EDM (only in signal mode)"),
	GRC_OLD_PLANE (1380, "Warning: inclination out of time range"),
	GRC_NO_PLANE (1381, "Warning: measurement without planeinclination correction"),
	GRC_INC_ERROR (1392, "Warning: measurement without sensorinclination correction"),
	GRC_INCLINE_ACC (1383, "Info : inclination accuracy can not be guaranteed"),
	GRC_MOT_UNREADY (1792, "motorization is not ready"),
	GRC_MOT_BUSY (1793, "motorization is handling another task"),
	GRC_MOT_NOT_OCONST (1794, "motorization is not in velocity mode"),
	GRC_MOT_NOT_CONFIG (1795, "motorization is in the wrong mode or busy"),
	GRC_MOT_NOT_POSIT (1796, "motorization is not in posit mode"),
	GRC_MOT_NOT_SERVICE (1797, "motorization is not in service mode"),
	GRC_MOT_NOT_BUSY (1798, "motorization is handling no task"),
	GRC_MOT_NOT_LOCK (1799, "motorization is not in tracking mode"),
	GRC_MOT_NOT_SPIRAL (1800, "motorization is not in spiral mode"),
	GRC_MOT_V_ENCODER (1801, "vertical encoder/motor error"),
	GRC_MOT_HZ_ENCODER (1802, "horizontal encoder/motor error"),
	GRC_MOT_HZ_V_ENCODER (1803, "horizontal and vertical encoder/motor error"),
	GRC_MOT_HZ_MOTOR_ERROR (1804, "azimuth motor error"),
	GRC_MOT_V_MOTOR_ERROR (1805, "elevation motor error"),
	GRC_MOT_TIMEOUT (1806, "general timeout"),
	GRC_MOT_HZ_TIMEOUT (1807, "timeout of azimuth positioning system"),
	GRC_MOT_V_TIMEOUT (1808, "timeout of elevation positioning system"),
	GRC_MOT_SCAN_STOPPED (1809, "scan stopped with error"),
	GRC_MOT_SUPPLY_CHANGED (1810, "scan paused because power supply has changed"),
	GRC_COM_ERO (3072, "Initiate Extended Runtime Operation (ERO)."),
	GRC_COM_CANT_ENCODE (3073, "Cannot encode arguments in client."),
	GRC_COM_CANT_DECODE (3074, "Cannot decode results in client."),
	GRC_COM_CANT_SEND (3075, "Hardware error while sending."),
	GRC_COM_CANT_RECV (3076, "Hardware error while receiving."),
	GRC_COM_TIMEDOUT (3077, "Request timed out."),
	GRC_COM_WRONG_FORMAT (3078, "Packet format error."),
	GRC_COM_VER_MISMATCH (3079, "Version mismatch between client and server."),
	GRC_COM_CANT_DECODE_REQ (3080, "Cannot decode arguments in server."),
	GRC_COM_PROC_UNAVAIL (3081, "Unknown RPC, procedure ID invalid."),
	GRC_COM_CANT_ENCODE_REP (3082, "Cannot encode results in server."),
	GRC_COM_SYSTEM_ERR (3083, "Unspecified generic system error."),
	GRC_COM_FAILED (3085, "Unspecified error."),
	GRC_COM_NO_BINARY (3086, "Binary protocol not available."),
	GRC_COM_INTR (3087, "Call interrupted."),
	GRC_COM_REQUIRES_8DBITS (3090, "Protocol needs 8bit encoded characters."),
	GRC_COM_TR_ID_MISMATCH (3093, "TRANSACTIONS ID mismatch error."),
	GRC_COM_NOT_GEOCOM (3094, "Protocol not recognizable."),
	GRC_COM_UNKNOWN_PORT (3095, "(WIN) Invalid port address."),
	GRC_COM_ERO_END (3099, "ERO is terminating."),
	GRC_COM_OVERRUN (3100, "Internal error: data buffer overflow."),
	GRC_COM_SRVR_RX_CHECKSUM_ERRR (3101, "Invalid checksum on server side received."),
	GRC_COM_CLNT_RX_CHECKSUM_ERRR (3102, "Invalid checksum on client side received."),
	GRC_COM_PORT_NOT_AVAILABLE (3103, "(WIN) Port not available."),
	GRC_COM_PORT_NOT_OPEN (3104, "(WIN) Port not opened."),
	GRC_COM_NO_PARTNER (3105, "(WIN) Unable to find TPS."),
	GRC_COM_ERO_NOT_STARTED (3106, "Extended Runtime Operation could not be started."),
	GRC_COM_CONS_REQ (3107, "Att to send cons reqs"),
	GRC_COM_SRVR_IS_SLEEPING (3108, "TPS has gone to sleep. Wait and try again."),
	GRC_COM_SRVR_IS_OFF (3109, "TPS has shut down. Wait and try again."),
	GRC_COM_NO_CHECKSUM (3110, "No checksum in ASCII protocol available."),
	GRC_AUT_TIMEOUT (8704, "Position not reached"),
	GRC_AUT_DETENT_ERROR (8705, "Positioning not possible due to mounted EDM"),
	GRC_AUT_ANGLE_ERROR (8706, "Angle measurement error"),
	GRC_AUT_MOTOR_ERROR (8707, "Motorisation error"),
	GRC_AUT_INCACC (8708, "Position not exactly reached"),
	GRC_AUT_DEV_ERROR (8709, "Deviation measurement error"),
	GRC_AUT_NO_TARGET (8710, "No target detected"),
	GRC_AUT_MULTIPLE_TARGETS (8711, "Multiple target detected"),
	GRC_AUT_BAD_ENVIRONMENT (8712, "Bad environment conditions"),
	GRC_AUT_DETECTOR_ERROR (8713, "Error in target acquisition"),
	GRC_AUT_NOT_ENABLED (8714, "Target acquisition not enabled"),
	GRC_AUT_CALACC (8715, "ATR-Calibration failed"),
	GRC_AUT_ACCURACY (8716, "Target position not exactly reached"),
	GRC_AUT_DIST_STARTED (8717, "Info: dist. measurement has been started"),
	GRC_AUT_SUPPLY_TOO_HIGH (8718, "external Supply voltage is too high"),
	GRC_AUT_SUPPLY_TOO_LOW (8719, "int. or ext. Supply voltage is too low"),
	GRC_AUT_NO_WORKING_AREA (8720, "working area not set"),
	GRC_AUT_ARRAY_FULL (8721, "power search data array is filled"),
	GRC_AUT_NO_DATA (8722, "no data available"),
	GRC_AUT_SIDECOVER_ERR (8723, "motion cannot be executed because of sidecover"),
	GRC_AUT_OUT_OF_SYNC (8724, "angle requested for time not in collection (probably telescope out of sync)"),
	GRC_AUT_NO_LOCK (8725, "lock mode not allowed"),
	GRC_KDM_NOT_AVAILABLE (12544, "KDM device is not available."),
	GRC_FTR_FILEACCESS (13056, "File access error"),
	GRC_FTR_WRONGFILEBLOCKNUMBER (13057, "block number was not the expected one"),
	GRC_FTR_NOTENOUGHSPACE (13058, "not enough space on device to proceed uploading"),
	GRC_FTR_INVALIDINPUT (13059, "Rename of file failed."),
	GRC_FTR_MISSINGSETUP (13060, "invalid parameter as input"),
	GRC_CAM_NOT_READY (13824, "CAM-System is not ready"),
	GRC_CAM_NOT_INIT (13825, "Camera is not initialised"),
	GRC_CAM_IMG_NOT_AVAILABLE (13826, "Image from the camera is not available"),
	GRC_CAM_IMAGE_SAVING_ERROR (13828, "Error while saving image"),
	GRC_CAM_BIT_DEPTH_ERROR (13834, "Bit depth of the image is wrong"),
	GRC_CAM_OUT_OF_MEMORY (13835, "There is no memory available"),
	GRC_CAM_SPOT_NOT_AVAIL (13836, "Required spot is not available"),
	GRC_CAM_NO_SPOTS_INLIST (13837, "Spot list is empty"),
	GRC_CAM_NO_TARGET (13838, "There are no spots in image"),
	GRC_CAM_TARGET_NOT_FOUND (13839, "Required target is not found"),
	GRC_CAM_NO_CALIB_INPUT_DATA (13844, "Calibration input data is missing"),
	GRC_CAM_MEAS_NOT_ACCURATE (13845, "Measurement is not accurate"),
	GRC_CAM_DIRTY (13854, "Camera cleanness check failed, camera is dirty"),
	GRC_CAM_AF_FAILED (13864, "AF failed");

	private final int value;
	private String description;
	
	private GRC(int value, String description) {
		this.value = value;
		this.description = description;
	}
	
	public int getValue() {
		return value;
	}
	
	public String toString() {
		return this.name() + "(" + this.value + "): " + this.description;
	}
	
	public String getDescription() {
		return this.description;
	}

	public static GRC getEnumByValue(int value) {
		for(GRC element : GRC.values()) {
			if(element.getValue() == value)
				return element;
		}
		return null;
	}  
}
